services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fiery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  be:
    build: ./be
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/fiery_db?schema=public"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: "http://localhost:3001"
      FRONTEND_URL: "http://localhost:5173"
    depends_on:
      - db

volumes:
  postgres_data:
